version: "3.2"
services:
  go:
    build: .
    depends_on:
      - proxy_mysql
    ports:
      - "3001:8080"
    volumes:
      - .:/go/src/github.com/edenriquez/load-balancer-proxy-go
    command: "go run api/main.go"
  proxy_mysql:
    image: mysql:5.6.40
    environment:
      - MYSQL_DATABASE=proxy
      - MYSQL_ROOT_PASSWORD=pass
